project_id = "zdfsqhrfnkdwtyipfisb"

[functions.discogs]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.identify-record]
verify_jwt = false

[functions.grade-vinyl]
verify_jwt = false
